#+author: bazaluga (bzalugas)

* tester-libft
tester-libft is my personal tester for my 42's libft project. This is not the official tests but only the ones I think are important. The best thing to do is to use the maximum tests/testers to be sure your libft is perfect.

* IMPORTANT INFORMATION
** Running tests on ubuntu
If you run the tests on ubuntu machine (with same version as 42), you can use normal tests. These tests compare original libc's function with your function.
** Running tests on other OS
I also created a "static" version, that doesn't compare normal libc's function with yours in special cases, like passing NULL, because the behaviors can be different regarding the OS. To use it, run ~make static~.

* Installation
The default structure is:
#+begin_example
.
|- libft/
|- tester-libft/
#+end_example
Change the location of your ~libft.a~ in the Makefile (variable LIBFT) if needed. Don't forget to also change the location of ~libft.h~ in ~lftest.h~

* Usage
Just run ~make run~ and the Makefile will build your libft & launch the tests.

If you want to run "static tests", run ~make static~.

* Informations
The tester-libft uses [[https://cutest.sourceforge.net/][CuTest]] for unit testing every function of the libft. It is really simple to use and it takes only 2 files to work. If you want to create your own unit tests or modify mine, you can do so easily.
