#+title: Libft tests description
* Mandatory part
** ft_isalnum
** ft_isalpha
** ft_isascii
** ft_isdigit
** ft_isprint
** ft_strlen
** ft_memset
** ft_bzero
** ft_memcpy
*** Basic input
Basic use of the function.
*** Smaller n
Normal input but with n < strlen(input).
*** n = 0
Normal input but with n = 0.
*** destination & source the same
dst & src pointing on same address.
*** NULL destination
dst set to NULL.
Behavior on ubuntu: segfault.
*** NULL source
src set to NULL.
Behavior on ubuntu: segfault.
*** Both destination & source NULL
dst & src set to NULL.
Behavior on ubuntu: segfault.
** ft_memmove
*** Basic input
Basic use of the function.
*** destination & source the same
dst & src pointing on same address.
*** Overlapping : destination lower than source
dst address set to a lower address than src but with an overlapping size.
*** Overlapping : source lower than destination
src address set to a lower address than dst but with an overlapping size.
*** Smaller n
Normal input but with n < strlen(input).
*** n = 0
Normal input but with n = 0.
*** NULL destination
dst set to NULL.
Behavior on ubuntu: segfault.
*** NULL source
src set to NULL.
Behavior on ubuntu: segfault.
*** Both destination & source NULL
dst & src set to NULL.
Behavior on ubuntu: segfault.

** TODO ft_strlcpy [0/10]
*** CODE Basic input
Basic use of the function.
Behavior: copies size-1 bytes from src to dst + \0.
Return value: length of src.
*** CODE Smaller size
Size smaller than src.
Behavior: copies size-1 bytes from src to dst + \0.
Return value: length of src.
*** CODE Bigger size
Size bigger than src.
Behavior: copies only strlen(src) bytes from src to dst.
Return value: length of src.
*** CODE Size zero
size = 0.
Behavior: doesn't copy anything.
Return value: length of src.
*** CODE dst too small
Normal src & size but size of dst too small.
Behavior: copies size-1 bytes from src to dst + \0 (cans segfault).
Return value: length of src.
*** CODE dst overlapping src
dst address set to a lower adress than src but with an overlapping size.
Behavior: copies size-1 bytes from src to dst + \0.
Return value: length of src (after the copy).
*** CODE src overlapping dst
src address set to a lower adress than dst but with an overlapping size.
Behavior: copies size-1 bytes from src to dst + \0.
Return value: length of src (after the copy).
*** CODE NULL dst
dst set to NULL.
Behavior: SEGFAULT.
*** CODE NULL src
src set to NULL.
Behavior: SEGFAULT.
*** CODE NULL dst & src
dst & src set to NULL.
Behavior: SEGFAULT.
** ft_strlcat
** ft_toupper
** ft_tolower
** ft_strchr
** ft_strrchr
** ft_strncmp
** ft_memchr
** ft_memcmp
** ft_strnstr
** ft_atoi
** ft_calloc
** ft_strdup
** ft_substr
** ft_strjoin
** ft_strtrim
** ft_split
** ft_itoa
** ft_strmapi
** ft_striteri
** ft_putchar_fd
** ft_putstr_fd
** ft_putendl_fd
** ft_putnbr_fd

* Bonus part
** ft_lstnew
** ft_lstadd_front
** ft_lstsize
** ft_lstlast
** ft_lastadd_back
** ft_lstdelone
** ft_lstclear
** ft_lstiter
** ft_lstmap
