* Libft tests description
** ft_isalnum
** ft_isalpha
** ft_isascii
** ft_isdigit
** ft_isprint
** ft_strlen
** ft_memset
** ft_bzero
** ft_memcpy
*** Basic input
Basic use of the function.
*** Smaller n
Normal input but with n < strlen(input).
*** n = 0
Normal input but with n = 0.
*** destination & source the same
dst & src pointing on same address.
*** NULL destination
dst set to NULL.
Behavior on ubuntu: segfault.
*** NULL source
src set to NULL.
Behavior on ubuntu: segfault.
*** Both destination & source NULL
dst & src set to NULL.
Behavior on ubuntu: segfault.
** ft_memmove
*** Basic input
Basic use of the function.
*** destination & source the same
dst & src pointing on same address.
*** Overlapping : destination lower than source
dst address set to a lower address than src but with an overlapping length.
*** Overlapping : source lower than destination
src address set to a lower address than dst but with an overlapping length.
*** Smaller n
Normal input but with n < strlen(input).
*** n = 0
Normal input but with n = 0.
*** NULL destination
dst set to NULL.
Behavior on ubuntu: segfault.
*** NULL source
src set to NULL.
Behavior on ubuntu: segfault.
*** Both destination & source NULL
dst & src set to NULL.
Behavior on ubuntu: segfault.
